package interfaz;

import vistas.VistaProductosCompradosRecientemente;

public class Productos_comprados_recientemente extends VistaProductosCompradosRecientemente{
	public Ver_ultimas_compras _ver_ultimas_compras;
	public Producto_comprado_recientemente _producto_comprado_recientemente;
}